export const SEND_COUNTRIES_REQUEST = "SEND_COUNTRIES_REQUEST"
export const RECEIVE_COUNTRIES_RESPONSE = "RECEIVE_COUNTRIES_RESPONSE"
export const RECEIVE_COUNTRIES_ERROR = "RECEIVE_COUNTRIES_ERROR"
export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY"